package graficoss;

import java.text.NumberFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author solda
 */
public class miVentana extends javax.swing.JFrame {

    private double num1, num2, result;

    /**
     * Creates new form miVentana
     */
    public miVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BotobtnSumar = new javax.swing.JButton();
        BotonbtnRestar = new javax.swing.JButton();
        BotonbtnMultiplicar = new javax.swing.JButton();
        BotonbtnDividir = new javax.swing.JButton();
        BotonbtnReciduos = new javax.swing.JButton();
        txtSegundoNumero = new javax.swing.JTextField();
        txtPrimerNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        BotobtnSumar.setText("Suma");
        BotobtnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotobtnSumarActionPerformed(evt);
            }
        });
        getContentPane().add(BotobtnSumar);
        BotobtnSumar.setBounds(10, 10, 120, 23);

        BotonbtnRestar.setText("Resta");
        BotonbtnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonbtnRestarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonbtnRestar);
        BotonbtnRestar.setBounds(10, 50, 120, 23);

        BotonbtnMultiplicar.setText("Multiplicacion");
        BotonbtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonbtnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonbtnMultiplicar);
        BotonbtnMultiplicar.setBounds(10, 90, 120, 23);

        BotonbtnDividir.setText("Division");
        BotonbtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonbtnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonbtnDividir);
        BotonbtnDividir.setBounds(10, 130, 120, 23);

        BotonbtnReciduos.setText("Reciduos");
        BotonbtnReciduos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonbtnReciduosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonbtnReciduos);
        BotonbtnReciduos.setBounds(10, 180, 120, 20);
        getContentPane().add(txtSegundoNumero);
        txtSegundoNumero.setBounds(300, 100, 90, 40);

        txtPrimerNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrimerNumero);
        txtPrimerNumero.setBounds(300, 40, 90, 40);

        jLabel1.setText("Primer valor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 50, 120, 20);

        jLabel2.setText("Segundo numero");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 120, 120, 20);

        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(160, 180, 120, 20);

        txtResultado.setBorder(null);
        txtResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtResultado, org.jdesktop.beansbinding.ELProperty.create("false"), txtResultado, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtResultado);
        txtResultado.setBounds(300, 170, 90, 40);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotobtnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotobtnSumarActionPerformed
        // TODO add your handling code here:
        do {
            num1 = Double.parseDouble(txtPrimerNumero.getText());
            num2 = Double.parseDouble(txtSegundoNumero.getText());
            if (Character.isLetter((char) num2) == true || Character.isLetter((char) num1) == true) {
                JOptionPane.showMessageDialog(null, "ingrese solo numerossss");
            } else {
                result = num1 + num2;
                break;
            }
        } while (true);
        txtResultado.setText(String.valueOf(result));
    }//GEN-LAST:event_BotobtnSumarActionPerformed

    private void BotonbtnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonbtnRestarActionPerformed
        // TODO add your handling code here:
        double num1 = 0, num2 = 0, resultado = 0;
        try {
            num1 = Double.parseDouble(txtPrimerNumero.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ingrese un valor en la casilla uno");
        }
        num2 = Double.parseDouble(txtSegundoNumero.getText());
        resultado = num1 - num2;
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BotonbtnRestarActionPerformed

    private void BotonbtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonbtnMultiplicarActionPerformed
        // TODO add your handling code here:
        try {
            num1 = Double.parseDouble(txtPrimerNumero.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ingrese un valor en la casilla uno");
        }
        num2 = Double.parseDouble(txtSegundoNumero.getText());
        result = num1 * num2;
        txtResultado.setText(String.valueOf(result));
    }//GEN-LAST:event_BotonbtnMultiplicarActionPerformed

    private void BotonbtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonbtnDividirActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(txtPrimerNumero.getText());
        JOptionPane.showMessageDialog(null, "ingrese un valor en la casilla uno");
        num2 = Double.parseDouble(txtSegundoNumero.getText());
        result = num1 / num2;
        txtResultado.setText(String.valueOf(result));
    }//GEN-LAST:event_BotonbtnDividirActionPerformed

    private void BotonbtnReciduosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonbtnReciduosActionPerformed
        // TODO add your handling code here:
        double num1 = 0, num2 = 0, result = 0;
        try {
            num1 = Double.parseDouble(txtPrimerNumero.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ingrese un valor en la casilla uno");
        }
        num2 = Double.parseDouble(txtSegundoNumero.getText());
        result = num1 % num2;
        txtResultado.setText(String.valueOf(result));
    }//GEN-LAST:event_BotonbtnReciduosActionPerformed

    private void txtPrimerNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotobtnSumar;
    private javax.swing.JButton BotonbtnDividir;
    private javax.swing.JButton BotonbtnMultiplicar;
    private javax.swing.JButton BotonbtnReciduos;
    private javax.swing.JButton BotonbtnRestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtPrimerNumero;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtSegundoNumero;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
