/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biseccion;
import java.math.BigDecimal;
import java.math.RoundingMode;
import metodos.numericos.calcularRaiz;
/**
 *
 * @author kiuub
 */
public class MetodoReglaFalsaTrigonometrica extends javax.swing.JFrame {

    private double errorRelativo,funcionX0,funcionX1,funcionXr,funcionXrN,valorFuncionA,x0,valorFuncionB,valorPMedio,comparacionFunciones,porError,funcionPMedio;
    private  int cont=0;
    private  double x6,x5,x4,x3,x2,x1,c,valorAAux,valorBAux,compAPm,compBPm,decimales,funcionMAux,valorA,valorB;
    private String texto="";
    calcularRaiz metodo =null;
     
    /**
     * Creates new form metodoBiseccion
     */
    public MetodoReglaFalsaTrigonometrica() {
        //btnCalcular.setEnabled(false);
        initComponents();
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tbnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtConstante = new javax.swing.JTextField();
        txtSexta = new javax.swing.JTextField();
        txtQuinta = new javax.swing.JTextField();
        txtCuarta = new javax.swing.JTextField();
        txtCubica = new javax.swing.JTextField();
        txtCuadrada = new javax.swing.JTextField();
        txtLineal = new javax.swing.JTextField();
        txtFraccionAPi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFraccionBPi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaValores = new javax.swing.JTextArea();
        rbtnX6 = new javax.swing.JRadioButton();
        rbtnX5 = new javax.swing.JRadioButton();
        rbtnX4 = new javax.swing.JRadioButton();
        rbtnX3 = new javax.swing.JRadioButton();
        rbtnX2 = new javax.swing.JRadioButton();
        rbtnX = new javax.swing.JRadioButton();
        rbtnC = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        txtPorError = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDecimales = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        lblIteraciones = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtValorARangoGrados = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtValorBRangoGrados = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rbtnSeno = new javax.swing.JRadioButton();
        rbtnCoseno = new javax.swing.JRadioButton();
        rbtnTangente = new javax.swing.JRadioButton();
        txtValorARangoRadianes1 = new javax.swing.JTextField();
        txtValorBRangoRadianes1 = new javax.swing.JTextField();
        rbtnDecimalesPi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("false"), this, org.jdesktop.beansbinding.BeanProperty.create("resizable"));
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("x");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 20, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("6");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 20, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("x");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 20, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("5");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 20, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("x");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 20, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("4");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 20, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("x");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 20, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("3");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 20, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("x");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 20, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("2");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 20, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("c");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 20, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("x");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 20, -1));

        jLabel13.setBackground(java.awt.Color.black);
        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Rango");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        txtConstante.setText("0");
        jPanel1.add(txtConstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 60, -1));

        txtSexta.setText("0");
        jPanel1.add(txtSexta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        txtQuinta.setText("0");
        jPanel1.add(txtQuinta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));

        txtCuarta.setText("0");
        jPanel1.add(txtCuarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 50, -1));

        txtCubica.setText("0");
        jPanel1.add(txtCubica, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 50, -1));

        txtCuadrada.setText("0");
        jPanel1.add(txtCuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 60, -1));

        txtLineal.setText("0");
        jPanel1.add(txtLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 60, -1));

        txtFraccionAPi.setText("0");
        txtFraccionAPi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "a"));
        txtFraccionAPi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFraccionAPi.setEnabled(false);
        txtFraccionAPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraccionAPiActionPerformed(evt);
            }
        });
        jPanel1.add(txtFraccionAPi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText(",");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 10, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("]");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 10, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("[");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 10, 30));

        txtFraccionBPi.setText("0");
        txtFraccionBPi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "b"));
        txtFraccionBPi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFraccionBPi.setEnabled(false);
        txtFraccionBPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraccionBPiActionPerformed(evt);
            }
        });
        jPanel1.add(txtFraccionBPi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 140, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Metodo de la regla falsa Trigonometrica");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        txtAreaValores.setColumns(20);
        txtAreaValores.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txtAreaValores.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtAreaValores, org.jdesktop.beansbinding.ELProperty.create("false"), txtAreaValores, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(txtAreaValores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 310, 390));

        rbtnX6.setBackground(new java.awt.Color(255, 255, 255));
        rbtnX6.setText("si/no");
        rbtnX6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX6ActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnX6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        rbtnX5.setBackground(new java.awt.Color(255, 255, 255));
        rbtnX5.setText("si/no");
        rbtnX5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX5ActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnX5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        rbtnX4.setBackground(new java.awt.Color(255, 255, 255));
        rbtnX4.setText("si/no");
        rbtnX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX4ActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        rbtnX3.setBackground(new java.awt.Color(255, 255, 255));
        rbtnX3.setText("si/no");
        rbtnX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX3ActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        rbtnX2.setBackground(new java.awt.Color(255, 255, 255));
        rbtnX2.setText("si/no");
        rbtnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX2ActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        rbtnX.setBackground(new java.awt.Color(255, 255, 255));
        rbtnX.setText("si/no");
        rbtnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnXActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        rbtnC.setBackground(new java.awt.Color(255, 255, 255));
        rbtnC.setText("si/no");
        rbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel18.setText("% de error");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel1.add(txtPorError, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 200, -1));

        jLabel19.setText("Numero de decimales");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));
        jPanel1.add(txtDecimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 200, -1));

        btnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 90, 30));

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Numero de iteraciones: ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        lblIteraciones.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lblIteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 300, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("]");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 10, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("[");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 10, 30));

        txtValorARangoGrados.setText("0");
        txtValorARangoGrados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "a"));
        txtValorARangoGrados.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValorARangoGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorARangoGradosActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorARangoGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText(",");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 10, 30));

        txtValorBRangoGrados.setText("0");
        txtValorBRangoGrados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "b"));
        txtValorBRangoGrados.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValorBRangoGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorBRangoGradosActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorBRangoGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 140, -1));

        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Grados");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Radianes");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        rbtnSeno.setBackground(new java.awt.Color(255, 255, 255));
        tbnGroup.add(rbtnSeno);
        rbtnSeno.setText("Seno");
        jPanel1.add(rbtnSeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        rbtnCoseno.setBackground(new java.awt.Color(255, 255, 255));
        tbnGroup.add(rbtnCoseno);
        rbtnCoseno.setText("Coseno");
        jPanel1.add(rbtnCoseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        rbtnTangente.setBackground(new java.awt.Color(255, 255, 255));
        tbnGroup.add(rbtnTangente);
        rbtnTangente.setText("Tangente");
        jPanel1.add(rbtnTangente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        txtValorARangoRadianes1.setText("0");
        txtValorARangoRadianes1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "a"));
        txtValorARangoRadianes1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValorARangoRadianes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorARangoRadianes1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorARangoRadianes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, -1));

        txtValorBRangoRadianes1.setText("0");
        txtValorBRangoRadianes1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "b"));
        txtValorBRangoRadianes1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValorBRangoRadianes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorBRangoRadianes1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorBRangoRadianes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, -1));

        rbtnDecimalesPi.setBackground(new java.awt.Color(255, 255, 255));
        rbtnDecimalesPi.setText("fraccion de pi");
        rbtnDecimalesPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDecimalesPiActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnDecimalesPi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 100, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnX6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX6ActionPerformed
        // TODO add your handling code here:
        if (rbtnX6.isSelected()) {
            txtSexta.setText(String.valueOf(0));
            txtSexta.setEnabled(false);
        } else {
            txtSexta.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX6ActionPerformed

    private void rbtnX5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX5ActionPerformed
        // TODO add your handling code here:
        if (rbtnX5.isSelected()) {
            txtQuinta.setText(String.valueOf(0));
            txtQuinta.setEnabled(false);
        } else {
            txtQuinta.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX5ActionPerformed

    private void rbtnX4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX4ActionPerformed
        // TODO add your handling code here:
        if (rbtnX4.isSelected()) {
            txtCuarta.setText(String.valueOf(0));
            txtCuarta.setEnabled(false);
        } else {
            txtCuarta.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX4ActionPerformed

    private void rbtnX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX3ActionPerformed
        // TODO add your handling code here:
        if (rbtnX3.isSelected()) {
            txtCubica.setText(String.valueOf(0));
            txtCubica.setEnabled(false);
        } else {
            txtCubica.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX3ActionPerformed

    private void rbtnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX2ActionPerformed
        // TODO add your handling code here:
        if (rbtnX2.isSelected()) {
            txtCuadrada.setText(String.valueOf(0));
            txtCuadrada.setEnabled(false);
        } else {
            txtCuadrada.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX2ActionPerformed

    private void rbtnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnXActionPerformed
        // TODO add your handling code here:
        if (rbtnX.isSelected()) {
            txtLineal.setText(String.valueOf(0));
            txtLineal.setEnabled(false);
        } else {
            txtLineal.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnXActionPerformed

    private void rbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCActionPerformed
        // TODO add your handling code here:
        if (rbtnC.isSelected()) {
            txtConstante.setText(String.valueOf(0));
            txtConstante.setEnabled(false);
        } else {
            txtConstante.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnCActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        metodo =  new calcularRaiz();
        if(metodo.isNumberN(txtConstante.getText().trim())==false||metodo.isNumberN(txtLineal.getText().trim())==false||metodo.isNumberN(txtCuadrada.getText().trim())==false||metodo.isNumberN(txtCubica.getText().trim())==false||metodo.isNumberN(txtCuarta.getText().trim())==false||metodo.isNumberN(txtQuinta.getText().trim())==false||metodo.isNumberN(txtSexta.getText().trim())==false||metodo.isNumber(txtPorError.getText().trim())==false||metodo.isNumberN(txtFraccionAPi.getText().trim())==false||metodo.isNumberN(txtFraccionBPi.getText().trim())==false||metodo.isAInt(txtDecimales.getText().trim())==false||metodo.isNumberN(txtValorARangoGrados.getText().trim())==false||metodo.isNumberN(txtValorBRangoGrados.getText().trim())==false){
            txtAreaValores.setText("ingrese solo numeros");
        }
        else{
        x6=Double.parseDouble(String.valueOf(txtSexta.getText()));
        x5=Double.parseDouble(String.valueOf(txtQuinta.getText()));
        x4=Double.parseDouble(String.valueOf(txtCuarta.getText()));
        x3=Double.parseDouble(String.valueOf(txtCubica.getText()));
        x2=Double.parseDouble(String.valueOf(txtCuadrada.getText()));
        x1=Double.parseDouble(String.valueOf(txtLineal.getText()));
        c=Double.parseDouble(String.valueOf(txtConstante.getText()));
        if(rbtnDecimalesPi.isSelected()==true){
        valorA=(Double.parseDouble(String.valueOf(txtValorARangoRadianes1.getText()))*Math.PI)/(Double.parseDouble(String.valueOf(txtFraccionAPi.getText())));
        valorB=(Double.parseDouble(String.valueOf(txtValorBRangoRadianes1.getText()))*Math.PI)/(Double.parseDouble(String.valueOf(txtFraccionBPi.getText())));
       
        }
        else{
            valorA=(Double.parseDouble(String.valueOf(txtValorARangoRadianes1.getText()))*Math.PI);
            valorB=(Double.parseDouble(String.valueOf(txtValorBRangoRadianes1.getText()))*Math.PI);
        }
        if(rbtnSeno.isSelected()==true){
            valorFuncionA=Math.sin((x6*Math.pow(valorA, 6))+(x5*Math.pow(valorA, 5))+(x4*Math.pow(valorA, 4))+(x3*Math.pow(valorA, 3))+(x2*Math.pow(valorA, 2))+(x1*Math.pow(valorA, 1))+c);
            valorFuncionB=Math.sin((x6*Math.pow(valorB, 6))+(x5*Math.pow(valorB, 5))+(x4*Math.pow(valorB, 4))+(x3*Math.pow(valorB, 3))+(x2*Math.pow(valorB, 2))+(x1*Math.pow(valorB, 1))+c);
        
        }
          else if(rbtnCoseno.isSelected()==true){
             valorFuncionA=Math.cos((x6*Math.pow(valorA, 6))+(x5*Math.pow(valorA, 5))+(x4*Math.pow(valorA, 4))+(x3*Math.pow(valorA, 3))+(x2*Math.pow(valorA, 2))+(x1*Math.pow(valorA, 1))+c);
            valorFuncionB=Math.cos((x6*Math.pow(valorB, 6))+(x5*Math.pow(valorB, 5))+(x4*Math.pow(valorB, 4))+(x3*Math.pow(valorB, 3))+(x2*Math.pow(valorB, 2))+(x1*Math.pow(valorB, 1))+c);
        
              
          }
          else if(rbtnTangente.isSelected()==true){
              valorFuncionA=Math.tan((x6*Math.pow(valorA, 6))+(x5*Math.pow(valorA, 5))+(x4*Math.pow(valorA, 4))+(x3*Math.pow(valorA, 3))+(x2*Math.pow(valorA, 2))+(x1*Math.pow(valorA, 1))+c);
            valorFuncionB=Math.tan((x6*Math.pow(valorB, 6))+(x5*Math.pow(valorB, 5))+(x4*Math.pow(valorB, 4))+(x3*Math.pow(valorB, 3))+(x2*Math.pow(valorB, 2))+(x1*Math.pow(valorB, 1))+c);
        
              
          }
        decimales=Double.parseDouble(String.valueOf(txtDecimales.getText()));
        errorRelativo=0;
        funcionX0=valorFuncionA;
        funcionX1=valorFuncionB;
        porError=Double.parseDouble(String.valueOf(txtPorError.getText()));
        funcionXr=(((valorFuncionA*valorB)-(valorFuncionB*valorA))/(valorFuncionA-valorFuncionB));
        
        x0=funcionXr;
            /*BigDecimal decimalXr = new BigDecimal(x0);
            decimalXr = decimalXr.setScale((int)decimales, RoundingMode.HALF_UP);
            x0=decimalXr.doubleValue();
        */
            texto+="valor xr: "+ x0+"\n\n";
        if(valorA!=valorB || valorB!=valorA){
           
        do{
          if(rbtnSeno.isSelected()==true){
            funcionX0=Math.sin((x6*Math.pow(x0, 6))+(x5*Math.pow(x0, 5))+(x4*Math.pow(x0, 4))+(x3*Math.pow(x0, 3))+(x2*Math.pow(x0, 2))+(x1*Math.pow(x0, 1))+c);
          }
          else if(rbtnCoseno.isSelected()==true){
              funcionX0=Math.cos((x6*Math.pow(x0, 6))+(x5*Math.pow(x0, 5))+(x4*Math.pow(x0, 4))+(x3*Math.pow(x0, 3))+(x2*Math.pow(x0, 2))+(x1*Math.pow(x0, 1))+c);
          
          }
          else if(rbtnTangente.isSelected()==true){
              funcionX0=Math.tan((x6*Math.pow(x0, 6))+(x5*Math.pow(x0, 5))+(x4*Math.pow(x0, 4))+(x3*Math.pow(x0, 3))+(x2*Math.pow(x0, 2))+(x1*Math.pow(x0, 1))+c);
          
          }
            
            funcionXrN=((valorB)-(((funcionX1*x0)-(funcionX1*valorB))/(funcionX0-funcionX1)));
            /*BigDecimal decimalXrN = new BigDecimal(funcionXrN);
            decimalXrN = decimalXrN.setScale((int)decimales, RoundingMode.HALF_UP);
            funcionXrN=decimalXrN.doubleValue();
            */
            errorRelativo=Math.abs(((funcionXrN-x0)/funcionXrN)*100);
            
           /* BigDecimal decimalE = new BigDecimal(errorRelativo);
            decimalE = decimalE.setScale((int)decimales, RoundingMode.HALF_UP);
            errorRelativo=decimalE.doubleValue();
            */
            x0=funcionXrN;
           
            txtAreaValores.setText("iteracion ("+cont+")"+"\nerror Relativo: "+errorRelativo+"\nvalor de x: "+x0+"\n\n");
            texto+=txtAreaValores.getText();
            //System.out.println("iteracion: "+ cont+"\nerror Relativo: "+errorRelativo+"\nvalor del punto medio: "+valorPMedio+"\nvalor funcion(x): "+ funcionAux+"\nvalor b"+valorBAux+"\n\n");
           cont++;
          
        }while(errorRelativo>porError&&cont!=200);
        txtAreaValores.setText(texto);
        lblIteraciones.setText(String.valueOf(cont+"       valor de la raiz: "+ x0));
        cont=0;
        texto="";
        }else {
            txtAreaValores.setText("los rangos deben ser diferentes");
        }
        
        
        
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtFraccionAPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraccionAPiActionPerformed
        // TODO add your handling code here:
        //if(metodo.isNumberN(txtValorARangoRadianes.getText().trim())==false||metodo.isNumberN(txtValorBRangoRadianes.getText())==false||metodo.isNumberN(txtValorARangoGrados.getText().trim())==false||metodo.isNumberN(txtValorBRangoGrados.getText().trim())==false){
        double grados,radianes,grad;
        if(rbtnDecimalesPi.isSelected()==true){
        radianes =(Double.parseDouble(String.valueOf(txtValorARangoRadianes1.getText()))*Math.PI)/(Double.parseDouble(String.valueOf(txtFraccionAPi.getText())));
        }else{
            radianes =(Math.PI)*(Double.parseDouble(txtValorARangoRadianes1.getText()));
        }
        grados = Math.toDegrees(radianes);
        grad =grados;
        /* BigDecimal decimalRad = new BigDecimal(grad);
            decimalRad = decimalRad.setScale((int)decimales, RoundingMode.HALF_UP);
            grad=decimalRad.doubleValue();
        */
        txtValorARangoGrados.setText(String.valueOf(grad));
       
        //}
    }//GEN-LAST:event_txtFraccionAPiActionPerformed

    private void txtFraccionBPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraccionBPiActionPerformed

        // TODO add your handling code here:
        //if(metodo.isNumberN(txtValorARangoRadianes.getText().trim())==false||metodo.isNumberN(txtValorBRangoRadianes.getText())==false||metodo.isNumberN(txtValorARangoGrados.getText().trim())==false||metodo.isNumberN(txtValorBRangoGrados.getText().trim())==false){
         double grados,radianes,grad;
        if(rbtnDecimalesPi.isSelected()==true){
        radianes =(Double.parseDouble(String.valueOf(txtValorBRangoRadianes1.getText()))*Math.PI)/(Double.parseDouble(String.valueOf(txtFraccionBPi.getText())));
        }else{
            radianes =(Math.PI)*(Double.parseDouble(txtValorBRangoRadianes1.getText()));
        }
        grados = Math.toDegrees(radianes);
        grad=grados;
       /*BigDecimal decimalRad = new BigDecimal(grad);
            decimalRad = decimalRad.setScale((int)decimales, RoundingMode.HALF_UP);
            grad=decimalRad.doubleValue();
        */
        txtValorBRangoGrados.setText(String.valueOf(grad));
        //}
    }//GEN-LAST:event_txtFraccionBPiActionPerformed

    private void txtValorARangoGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorARangoGradosActionPerformed
        // TODO add your handling code here:
        //if(metodo.isNumberN(txtValorARangoRadianes.getText().trim())==false||metodo.isNumberN(txtValorBRangoRadianes.getText())==false||metodo.isNumberN(txtValorARangoGrados.getText().trim())==false||metodo.isNumberN(txtValorBRangoGrados.getText().trim())==false){
        double grados,radianes,rad;
        grados = Double.parseDouble(txtValorARangoGrados.getText());
        radianes = Math.toRadians(grados);
        rad = radianes;
        /*BigDecimal decimalGrad = new BigDecimal(rad);
            decimalGrad = decimalGrad.setScale((int)decimales, RoundingMode.HALF_UP);
            rad=decimalGrad.doubleValue();
        */
       txtValorARangoRadianes1.setText(String.valueOf(rad));
        //}
    }//GEN-LAST:event_txtValorARangoGradosActionPerformed

    private void txtValorBRangoGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorBRangoGradosActionPerformed
        // TODO add your handling code here:
        //if(metodo.isNumberN(txtValorARangoRadianes.getText().trim())==false||metodo.isNumberN(txtValorBRangoRadianes.getText())==false||metodo.isNumberN(txtValorARangoGrados.getText().trim())==false||metodo.isNumberN(txtValorBRangoGrados.getText().trim())==false){
         double grados,radianes,rad;
        grados = Double.parseDouble(txtValorBRangoGrados.getText());
        radianes = Math.toRadians(grados);
        rad=radianes;
        /* BigDecimal decimalGrad = new BigDecimal(rad);
            decimalGrad = decimalGrad.setScale((int)decimales, RoundingMode.HALF_UP);
            rad=decimalGrad.doubleValue();
        */
        txtValorBRangoRadianes1.setText(String.valueOf(rad));
        //}
    }//GEN-LAST:event_txtValorBRangoGradosActionPerformed

    private void txtValorARangoRadianes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorARangoRadianes1ActionPerformed
        // TODO add your handling code here:
        double grados,radianes,grad;
        if(rbtnDecimalesPi.isSelected()==true){
        radianes =(Double.parseDouble(String.valueOf(txtValorARangoRadianes1.getText()))*Math.PI)/(Double.parseDouble(String.valueOf(txtFraccionAPi.getText())));
        }else{
            radianes =(Math.PI)*(Double.parseDouble(txtValorARangoRadianes1.getText()));
        }
        grados = Math.toDegrees(radianes);
        grad =grados;
        /* BigDecimal decimalRad = new BigDecimal(grad);
            decimalRad = decimalRad.setScale((int)decimales, RoundingMode.HALF_UP);
            grad=decimalRad.doubleValue();
        */
        txtValorARangoGrados.setText(String.valueOf(grad));
    }//GEN-LAST:event_txtValorARangoRadianes1ActionPerformed

    private void txtValorBRangoRadianes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorBRangoRadianes1ActionPerformed
        // TODO add your handling code here:
         double grados,radianes,grad;
        if(rbtnDecimalesPi.isSelected()==true){
        radianes =(Double.parseDouble(String.valueOf(txtValorBRangoRadianes1.getText()))*Math.PI)/(Double.parseDouble(String.valueOf(txtFraccionBPi.getText())));
        }else{
            radianes =(Math.PI)*(Double.parseDouble(txtValorBRangoRadianes1.getText()));
        }
        grados = Math.toDegrees(radianes);
        grad=grados;
       /*BigDecimal decimalRad = new BigDecimal(grad);
            decimalRad = decimalRad.setScale((int)decimales, RoundingMode.HALF_UP);
            grad=decimalRad.doubleValue();
        */
        txtValorBRangoGrados.setText(String.valueOf(grad));
        //}
    }//GEN-LAST:event_txtValorBRangoRadianes1ActionPerformed

    private void rbtnDecimalesPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDecimalesPiActionPerformed
        // TODO add your handling code here:
        if(rbtnDecimalesPi.isSelected()==true){
            txtFraccionAPi.setEnabled(true);
            txtFraccionBPi.setEnabled(true);
           
        }else{
            txtFraccionAPi.setEnabled(false);
            txtFraccionBPi.setEnabled(false);
             txtFraccionAPi.setText("0");
             txtFraccionBPi.setText("0");
        }
        
    }//GEN-LAST:event_rbtnDecimalesPiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoReglaFalsaTrigonometrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoReglaFalsaTrigonometrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoReglaFalsaTrigonometrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoReglaFalsaTrigonometrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoReglaFalsaTrigonometrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIteraciones;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnCoseno;
    private javax.swing.JRadioButton rbtnDecimalesPi;
    private javax.swing.JRadioButton rbtnSeno;
    private javax.swing.JRadioButton rbtnTangente;
    private javax.swing.JRadioButton rbtnX;
    private javax.swing.JRadioButton rbtnX2;
    private javax.swing.JRadioButton rbtnX3;
    private javax.swing.JRadioButton rbtnX4;
    private javax.swing.JRadioButton rbtnX5;
    private javax.swing.JRadioButton rbtnX6;
    private javax.swing.ButtonGroup tbnGroup;
    private javax.swing.JTextArea txtAreaValores;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtCuadrada;
    private javax.swing.JTextField txtCuarta;
    private javax.swing.JTextField txtCubica;
    private javax.swing.JTextField txtDecimales;
    private javax.swing.JTextField txtFraccionAPi;
    private javax.swing.JTextField txtFraccionBPi;
    private javax.swing.JTextField txtLineal;
    private javax.swing.JTextField txtPorError;
    private javax.swing.JTextField txtQuinta;
    private javax.swing.JTextField txtSexta;
    private javax.swing.JTextField txtValorARangoGrados;
    private javax.swing.JTextField txtValorARangoRadianes1;
    private javax.swing.JTextField txtValorBRangoGrados;
    private javax.swing.JTextField txtValorBRangoRadianes1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
