/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package métodoSecante;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class MétodoSecante extends javax.swing.JFrame {

    DefaultTableModel modelo;
    private double AuxXO = 0;
    private int iteracion = 0;
    private double errorRelativoIteracion = 1.0;
    private double xi;
    private double fxi;
    private double roundedError = 0;
    private double roundedXi = 0;
    private String texto="";

    public MétodoSecante() {
        initComponents();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPorcentajeError = new javax.swing.JTextField();
        txtX6 = new javax.swing.JTextField();
        txtX5 = new javax.swing.JTextField();
        txtX4 = new javax.swing.JTextField();
        txtX3 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        txtX = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spinnerNumeroDecimales = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaR = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rbtnX6 = new javax.swing.JRadioButton();
        rbtnX5 = new javax.swing.JRadioButton();
        rbtnX4 = new javax.swing.JRadioButton();
        rbtnX3 = new javax.swing.JRadioButton();
        rbtnX2 = new javax.swing.JRadioButton();
        rbtnX = new javax.swing.JRadioButton();
        rbtnC = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Porcentaje de Error%: ");

        txtPorcentajeError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentajeErrorKeyTyped(evt);
            }
        });

        txtX6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX6KeyTyped(evt);
            }
        });

        txtX5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX5KeyTyped(evt);
            }
        });

        txtX4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX4KeyTyped(evt);
            }
        });

        txtX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX3KeyTyped(evt);
            }
        });

        txtX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX2KeyTyped(evt);
            }
        });

        txtX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtXKeyTyped(evt);
            }
        });

        txtC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("f(x)");

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Número de Decimales: ");

        spinnerNumeroDecimales.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("INTERVALO: ");

        txtA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("[");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("  a");

        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("]");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText(" b");

        botonIniciar.setBackground(new java.awt.Color(204, 204, 204));
        botonIniciar.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        botonIniciar.setText("Calcular");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        txtAreaR.setColumns(20);
        txtAreaR.setRows(5);
        jScrollPane2.setViewportView(txtAreaR);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("x");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("6");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("x");

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("5");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("x");

        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("4");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("x");

        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("3");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("x");

        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("2");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("x");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("c");

        rbtnX6.setBackground(new java.awt.Color(51, 51, 51));
        rbtnX6.setForeground(new java.awt.Color(204, 204, 204));
        rbtnX6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX6ActionPerformed(evt);
            }
        });

        rbtnX5.setBackground(new java.awt.Color(51, 51, 51));
        rbtnX5.setForeground(new java.awt.Color(204, 204, 204));
        rbtnX5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX5ActionPerformed(evt);
            }
        });

        rbtnX4.setBackground(new java.awt.Color(51, 51, 51));
        rbtnX4.setForeground(new java.awt.Color(204, 204, 204));
        rbtnX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX4ActionPerformed(evt);
            }
        });

        rbtnX3.setBackground(new java.awt.Color(51, 51, 51));
        rbtnX3.setForeground(new java.awt.Color(204, 204, 204));
        rbtnX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX3ActionPerformed(evt);
            }
        });

        rbtnX2.setBackground(new java.awt.Color(51, 51, 51));
        rbtnX2.setForeground(new java.awt.Color(204, 204, 204));
        rbtnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnX2ActionPerformed(evt);
            }
        });

        rbtnX.setBackground(new java.awt.Color(51, 51, 51));
        rbtnX.setForeground(new java.awt.Color(204, 204, 204));
        rbtnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnXActionPerformed(evt);
            }
        });

        rbtnC.setBackground(new java.awt.Color(51, 51, 51));
        rbtnC.setForeground(new java.awt.Color(204, 204, 204));
        rbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Metodo de la secante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPorcentajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerNumeroDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtX6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnX6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtX5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtX4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnX5)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnX4)))
                                .addGap(16, 16, 16)
                                .addComponent(rbtnX3)
                                .addGap(28, 28, 28)
                                .addComponent(rbtnX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel15))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(txtX3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rbtnX)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnC)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtX6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnX6)
                                    .addComponent(rbtnX5)
                                    .addComponent(rbtnX4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtnX3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtnX2)
                                    .addComponent(rbtnX, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtnC, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcentajeError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(spinnerNumeroDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPorcentajeErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeErrorKeyTyped
        char c = evt.getKeyChar();
        //Con punto decimal
        if ((c >= 33 && c <= 45) || (c == 47) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtPorcentajeErrorKeyTyped

    private void txtX6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX6KeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtX6KeyTyped

    private void txtX5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX5KeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtX5KeyTyped

    private void txtX4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX4KeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtX4KeyTyped

    private void txtX3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX3KeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtX3KeyTyped

    private void txtX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX2KeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtX2KeyTyped

    private void txtXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtXKeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtXKeyTyped

    private void txtCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCKeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtCKeyTyped

    private void txtAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAKeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || c == 47 || c == 46 || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtAKeyTyped

    private void txtBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyTyped
        char c = evt.getKeyChar();
        //Sin punto decimal puros enteros
        if ((c >= 33 && c <= 44) || c == 47 || c == 46 || (c >= 58 && c <= 253)) {
            evt.consume();
        } else {
        }
    }//GEN-LAST:event_txtBKeyTyped

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed

       try{
        //porcentaje de error
        double porcentajeError = Double.parseDouble(txtPorcentajeError.getText());
        //Valores de la función
        double x6 = Double.parseDouble(txtX6.getText());
        double x5 = Double.parseDouble(txtX5.getText());
        double x4 = Double.parseDouble(txtX4.getText());
        double x3 = Double.parseDouble(txtX3.getText());
        double x2 = Double.parseDouble(txtX2.getText());
        double x = Double.parseDouble(txtX.getText());
        double c = Double.parseDouble(txtC.getText());

        //Valores del Intervalo.
        double xiMenos1 = Integer.parseInt(txtA.getText());
        xi = Integer.parseInt(txtB.getText());
        double b = xi;

        //Valores Para los Raounded
        int decimal1 = (int) (Math.pow(10, (int) spinnerNumeroDecimales.getValue()));
        double decimal2 = (double) decimal1;
        //Cálculo de funcion fxi
        double fxiMenos1 = x6 * (Math.pow(xiMenos1, 6)) + x5 * (Math.pow(xiMenos1, 5)) + x4 * (Math.pow(xiMenos1, 4)) + x3 * (Math.pow(xiMenos1, 3))
                + x2 * (Math.pow(xiMenos1, 2))
                + x * (Math.pow(xiMenos1, 1)) + c;
        //Cálculo de función fxi-1
        fxi = x6 * (Math.pow(xi, 6)) + x5 * (Math.pow(xi, 5)) + x4 * (Math.pow(xi, 4))
                + x3 * (Math.pow(xi, 3)) + x2 * (Math.pow(xi, 2))
                + x * (Math.pow(xi, 1)) + c;
        System.out.println("Función xi-1: " + fxiMenos1);
        System.out.println("Función xi: " + fxi);

        //Primera iteración a la raíz
        iteracion = 1;
        xi = xi - (((fxi) * (xiMenos1 - xi)) / ((fxiMenos1) - (fxi)));
        System.out.println("Primera Iteración: " + xi);

        xiMenos1 = b;
        b = xi;
        System.out.println("Intervalo a: " + xiMenos1);
        System.out.println("Intervalo b: " + b + "\n\n");

        //Comienza las iteraciónes
        do {
            iteracion++;
            fxiMenos1 = x6 * (Math.pow(xiMenos1, 6)) + x5 * (Math.pow(xiMenos1, 5)) + x4 * (Math.pow(xiMenos1, 4)) + x3 * (Math.pow(xiMenos1, 3))
                    + x2 * (Math.pow(xiMenos1, 2))
                    + x * (Math.pow(xiMenos1, 1)) + c;
            //Cálculo de función fxi-1
            fxi = x6 * (Math.pow(xi, 6)) + x5 * (Math.pow(xi, 5)) + x4 * (Math.pow(xi, 4))
                    + x3 * (Math.pow(xi, 3)) + x2 * (Math.pow(xi, 2))
                    + x * (Math.pow(xi, 1)) + c;
            System.out.println("Función xi-1: " + fxiMenos1);
            System.out.println("Función xi: " + fxi);
            System.out.println("\n");

            xi = xi - (((fxi) * (xiMenos1 - xi)) / ((fxiMenos1) - (fxi)));
            System.out.println("RESULTADO DE xi: " + xi);
            errorRelativoIteracion = Math.abs(((xi - b) / xi)*100);
            System.out.println("ERROR: " + errorRelativoIteracion);

            xiMenos1 = b;
            b = xi;
            System.out.println("Intervalo xi-1: " + xiMenos1);
            System.out.println("Intervalo xi: " + b + "\n\n");

            roundedError = Math.round(errorRelativoIteracion * decimal1) / decimal2;
            roundedXi = Math.round(xi * decimal1) / decimal2;
            System.out.println("Error% ROUNDED:" + errorRelativoIteracion);

            //Object datos[] = {iteracion, roundedError, roundedXi};
           
            txtAreaR.setText("iteracion ("+iteracion+")"+"\nerror Relativo: "+roundedError+"\nvalor de x: "+roundedXi+"\n\n");
            texto+=txtAreaR.getText();
        } while (iteracion <= 30 && porcentajeError <= roundedError);
         txtAreaR.setText(texto);
       
     
        texto="";
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"llene los datos porfavor");
        }

    }//GEN-LAST:event_botonIniciarActionPerformed

    private void rbtnX6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX6ActionPerformed
        // TODO add your handling code here:
        if (rbtnX6.isSelected()) {
            txtX6.setText(String.valueOf(0));
            txtX6.setEnabled(false);
        } else {
            txtX6.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX6ActionPerformed

    private void rbtnX5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX5ActionPerformed
        // TODO add your handling code here:
        if (rbtnX5.isSelected()) {
            txtX5.setText(String.valueOf(0));
            txtX5.setEnabled(false);
        } else {
            txtX5.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX5ActionPerformed

    private void rbtnX4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX4ActionPerformed
        // TODO add your handling code here:
        if (rbtnX4.isSelected()) {
            txtX4.setText(String.valueOf(0));
            txtX4.setEnabled(false);
        } else {
            txtX4.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX4ActionPerformed

    private void rbtnX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX3ActionPerformed
        // TODO add your handling code here:
        if (rbtnX3.isSelected()) {
            txtX3.setText(String.valueOf(0));
            txtX3.setEnabled(false);
        } else {
            txtX3.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX3ActionPerformed

    private void rbtnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnX2ActionPerformed
        // TODO add your handling code here:
        if (rbtnX2.isSelected()) {
            txtX2.setText(String.valueOf(0));
            txtX2.setEnabled(false);
        } else {
            txtX2.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnX2ActionPerformed

    private void rbtnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnXActionPerformed
        // TODO add your handling code here:
        if (rbtnX.isSelected()) {
            txtX.setText(String.valueOf(0));
            txtX.setEnabled(false);
        } else {
            txtX.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnXActionPerformed

    private void rbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCActionPerformed
        // TODO add your handling code here:
        if (rbtnC.isSelected()) {
            txtC.setText(String.valueOf(0));
            txtC.setEnabled(false);
        } else {
            txtC.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MétodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MétodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MétodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MétodoSecante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MétodoSecante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnX;
    private javax.swing.JRadioButton rbtnX2;
    private javax.swing.JRadioButton rbtnX3;
    private javax.swing.JRadioButton rbtnX4;
    private javax.swing.JRadioButton rbtnX5;
    private javax.swing.JRadioButton rbtnX6;
    private javax.swing.JSpinner spinnerNumeroDecimales;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextArea txtAreaR;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtPorcentajeError;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX3;
    private javax.swing.JTextField txtX4;
    private javax.swing.JTextField txtX5;
    private javax.swing.JTextField txtX6;
    // End of variables declaration//GEN-END:variables
}
