/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/**
 *
 * @author Axel Ordoñez
 */
public class RaizDeC extends javax.swing.JFrame {

    /**
     * Creates new form RaizDeC
     */
    public RaizDeC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorDeX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPorcentajeDeError = new javax.swing.JTextField();
        spinnerNumeroDeDecimales = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        BotonGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor de C");

        jLabel2.setText("Valor de X");

        txtValorDeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDeXActionPerformed(evt);
            }
        });

        jLabel3.setText("% de Error");

        txtPorcentajeDeError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeDeErrorActionPerformed(evt);
            }
        });

        spinnerNumeroDeDecimales.setModel(new javax.swing.SpinnerNumberModel(0, 0, 11, 1));

        jLabel4.setText("Numero de Decimales");

        BotonGenerar.setText("Generar");
        BotonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonGenerar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtC)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorDeX))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPorcentajeDeError)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerNumeroDeDecimales))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtC, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtValorDeX)
                    .addComponent(txtPorcentajeDeError)
                    .addComponent(spinnerNumeroDeDecimales))
                .addGap(46, 46, 46)
                .addComponent(BotonGenerar)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarActionPerformed
        // TODO add your handling code here:
        double NuevoError, nuevoC = 0, nuevaX, C, x = 0;
        int Cont = 0;
        int decimales = (int) spinnerNumeroDeDecimales.getValue();
        C = Double.parseDouble(txtC.getText());
        nuevaX = Double.parseDouble(txtValorDeX.getText());
        if ((!txtC.getText().equals("")) || (!txtPorcentajeDeError.getText().equals("")) || (!txtValorDeX.getText().equals(""))) {
            do {
                Cont++;
                System.out.println("Numero de iteraciones: " + Cont);
                x = nuevaX;
                nuevoC = (.5) * (nuevaX + (C / nuevaX));
                nuevaX = nuevoC;
                BigDecimal db = new BigDecimal(nuevoC);
                db = db.setScale(decimales, RoundingMode.HALF_UP);
                System.out.println(db.doubleValue());
                NuevoError = (Math.abs(nuevoC - x) / x) * (100);
                BigDecimal db1 = new BigDecimal(NuevoError);
                db1 = db1.setScale(decimales, RoundingMode.HALF_UP);
                System.out.println("Su error relativo es de: " + db1.doubleValue());
                System.out.println("Er: " + NuevoError);
                nuevaX = nuevoC;
                System.out.println("---------------------------------------");
            } while (NuevoError >= Double.parseDouble(txtPorcentajeDeError.getText()));
            BigDecimal db = new BigDecimal(nuevoC);
            db = db.setScale(decimales, RoundingMode.HALF_UP);
            JOptionPane.showMessageDialog(null, "Raiz de " + C + ": "+db.doubleValue());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor llene todo los campos");
        }

    }//GEN-LAST:event_BotonGenerarActionPerformed

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void txtValorDeXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDeXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDeXActionPerformed

    private void txtPorcentajeDeErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeDeErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeDeErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaizDeC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaizDeC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaizDeC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaizDeC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaizDeC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinnerNumeroDeDecimales;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtPorcentajeDeError;
    private javax.swing.JTextField txtValorDeX;
    // End of variables declaration//GEN-END:variables
}
